/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/coffre-minecraft.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useSpring, a } from "@react-spring/three";

import chestOpenSound from "../../assets/sound/open-case.mp3";
import chestCloseSound from "../../assets/sound/close-case.mp3";
const openChest = new Audio(chestOpenSound);
const closeChest = new Audio(chestCloseSound);

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../models/coffre-minecraft.glb"
  );
  const actions = useRef();
  const [mixer] = useState(() => new THREE.AnimationMixer());
  useFrame((state, delta) => mixer.update(delta));
  useEffect(() => {
    actions.current = {
      ArmatureAction: mixer.clipAction(animations[0], group.current),
    };
    return () => animations.forEach((clip) => mixer.uncacheClip(clip));
  }, [animations, mixer]);

  // function for the case open & audio
  const handleAnimation = () => {
    props.setOpen(!props.open); // opposite of props.open from false to true
    if (props.open) {
      closeChest.volume = 0.3;
      closeChest.play();
    } else {
      openChest.volume = 0.3;
      openChest.play();
    }
  };

  // Chest open animation
  const chestOpen = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0], // rotate top half of chest when opened [open] : [close]
  });

  return (
    <group onClick={handleAnimation} ref={group} {...props} dispose={null}>
      <a.group position={[0, -0.99, 0]}>
        <group name="Scene">
          {/* <group name="Armature" position={[0, -0.985, 0]}> */}
          <group name="Armature" position={[0, 0, 0]}>
            <primitive object={nodes.Bone} /> {/* bottom half of chest*/}
            <a.primitive
              rotation={chestOpen.rotation}
              object={nodes.Bone001}
            />{" "}
            {/* top half of chest a.primitive since animated*/}
            <skinnedMesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Material}
              skeleton={nodes.Cube.skeleton}
            />
          </group>
        </group>
      </a.group>
    </group>
  );
}

useGLTF.preload("../../../models/coffre-minecraft.glb");
