/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/disc.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model() {
  const { nodes, materials } = useGLTF("../../../models/disc.glb");

  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Front.geometry}
        material={materials.Material}
        position={[0, 0.06, 0]}
      />
    </group>
  );
}

useGLTF.preload("../../../models/disc.glb");
